<?xml version="1.0" encoding="UTF-8"?>
<MessageMetadataDocument documentId="/home/makker/Projects/Java/CycloneFrontEnd/CycloneFrontEnd/tst/VIP001_OTAVIPVerwerkingsresultaatEPV20071107094822.xml" protocol="ebXML" protocolVersion="2.0">
	<Metadata name="From" type="urn:epv:sysda">VIP001_OTA</Metadata>
	<Metadata name="FromRole">Beantwoorden</Metadata>
	<Metadata name="To" type="urn:epv:sysda">RI2001_OTA</Metadata>
	<Metadata name="ToRole">Aanleveren</Metadata>
	<Metadata name="CPAId">CPA_VIP001_OTA_VIP_RI2001_OTA_EBS_3</Metadata>
	<Metadata name="ConversationId"/>
	<Metadata name="RefToMessageId"/>
	<Metadata name="Service" type="urn:epv:services">VipActualiserenEPV:0:8</Metadata>
	<Metadata name="Action">VIPVerwerkingsresultaatEPV</Metadata>
	<MessagePayloads>
		<Payload id="ID1">
			<MimeContentId>null</MimeContentId>
			<MimeContentType>application/xml</MimeContentType>
			<Location type="filePath">/home/makker/Projects/Java/CycloneFrontEnd/CycloneFrontEnd/tst/VIP001_OTAVIPVerwerkingsresultaatEPV20071107094822.xml</Location>
		</Payload>
	</MessagePayloads>
</MessageMetadataDocument>