<?xml version="1.0" encoding="UTF-8"?>
<MessageMetadataDocument documentId="Test_ZaakaanleveringOmSb" protocol="ebXML" protocolVersion="2.0">
	<Metadata name="From" type="urn:epv:sysda">VIP001_OTA</Metadata>
	<Metadata name="FromRole">Beantwoorden</Metadata>
	<Metadata name="To" type="urn:epv:sysda">RI2001_OTA</Metadata>
	<Metadata name="ToRole">Aanleveren</Metadata>
	<Metadata name="CPAId">CPA_VIP001_OTA_VIP_RI2001_OTA_EBS_3</Metadata>
	<Metadata name="ConversationId">VIPC2@20070919_01_mmd</Metadata>
	<Metadata name="RefToMessageId">1234</Metadata>
    <Metadata name="Service" type="urn:epv:services">VipActualiserenEPV:0:8</Metadata>
	<Metadata name="Action">VIPVerwerkingsresultaatEPV</Metadata>
	<MessagePayloads>
		<Payload id="ID1">
			<MimeContentId>12345@om-c2.sto.cjib.minjus.nl</MimeContentId>
			<MimeContentType>application/xml</MimeContentType>
			<Location type="filePath">C:\CycloneVIP\common\test\VIPVerwerkingsresultaatEPV-20090919.xml</Location>
		</Payload>
	</MessagePayloads>
</MessageMetadataDocument>